// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobApp = "job_apps"

// JobApp mapped from table <job_apps>
type JobApp struct {
	ID          int64          `gorm:"primarykey" json:"-"`
	CreatedAt   time.Time      `gorm:"autoCreateTime" json:"-"`
	DeletedAt   gorm.DeletedAt `gorm:"index" json:"-"`
	UpdatedAt   time.Time      `gorm:"autoUpdateTime" json:"-"`
	Status      string         `gorm:"default:applied" json:"-"` // status: applied, interview, offer, rejected, accepted
	Position    string         `json:"-"`                        // position applied for
	Company     string         `json:"-"`                        // company applied to
	DateApplied time.Time      `json:"-"`                        // date applied
	ResumeFile  string         `json:"-"`                        // resume file - this will be a link to the file under cfg.UploadsDir
	Notes       string         `json:"-"`                        // notes
}
