// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64          `gorm:"primarykey" json:"-"`
	CreatedAt    time.Time      `gorm:"autoCreateTime" json:"-"`
	DeletedAt    gorm.DeletedAt `gorm:"index" json:"-"`
	UpdatedAt    time.Time      `gorm:"autoUpdateTime" json:"-"`
	Username     string         `gorm:"uniqueIndex" json:"-"`
	FirstName    string         `json:"-"`
	LastName     string         `json:"-"`
	Email        string         `gorm:"uniqueIndex" json:"-"`
	Password     string         `json:"-"`
	IsAdmin      bool           `gorm:"index" json:"-"`
	Status       UserStatus     `gorm:"default:active" json:"-"` // status: active, disabled
	LastLoginAt  time.Time      `gorm:"index" json:"-"`
	ProfileImage string         `json:"-"`
}
